export const VEHICLE_CATEGORY = {
  car: [
    "Sedan",
    "SUV",
    "Off-Road Car",
    "Convertible",
    "Electric Car",
    "Luxury Car",
    "Sports Car",
    "Other Car",
  ],
  bike: [
    "Sports Bike",
    "Cruiser Bike",
    "Mountain Bike",
    "Dirt Bike",
    "Adventure Bike",
    "Standard Bike",
    "Other Bike",
  ],
  bicycle: [
    "Road Bicycle",
    "Mountain Bicycle",
    "Hybrid Bicycle",
    "Electric",
    "Other Bicycle",
  ],
  scooter: [
    "Electric Scooter",
    "Kick Scooter",
    "Standard Scooter",
    "Other Scooter",
  ],
};

export const ACCESSORIES_CATEGORY = [
  "Helmets",
  "Balaclava",
  "Paddock Stand",
  "Visor",
  "Brake Pad",
  "Engine Oil",
  "Vista MotoCare",
  "Chain Care",
  "RCB",
  "Motorcycle Baggage",
  "Jersey",
  "T-Shirt",
  "Intercom",
  "Bike Cover",
  "Gloves",
  "Tshirt",
  "Tyres",
  "Bike Accessories",
  "CAR Product",
  "Shooter",
  "Liqui Moly Package",
  "Rain Wear",
  "AGV K1",
  "Air Filter",
  "Cloth",
  "Boots",
  "Other",
];
